CREATE DATABASE IF NOT EXISTS biocombustivelehmais;

CREATE TABLE IF NOT EXISTS tbCADASTRO
(CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
LIXEIRA BOOLEAN NOT NULL DEFAULT 0,
PRIMARY KEY (CPF))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS tbCalculo
(ID_CALCULO INT NOT NULL AUTO_INCREMENT,
DATA DATE NULL,
ETANOL VARCHAR(100) NULL,
GASOLINA VARCHAR(100) NULL,
LITROS VARCHAR(100) NOT NULL,
CONSUMO DATE NULL,
RESULTADO VARCHAR(100) NOT NULL,
ID_CPF VARCHAR(11) NOT NULL,
PRIMARY KEY (ID_CALCULO),
CONSTRAINT FK_CPF_CALCULO
FOREIGN KEY (ID_CPF) REFERENCES tbCADASTRO (CPF))
ENGINE = InnoDB;


select * from tbcadastro;
alter table tbcadastro modify column senha varchar(100);